services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: HUGGING_FACE_KEY
        sync: false  # Set this in Render dashboard
